name: The Garden Brothers
favicon: null
layout_spectrum: 0.4617021
typography_spectrum: 0.2382979
title: Home Vegetable Garden Specialists
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#033001'
    - '#1FE903'
    - '#415D6E'
    - '#92A3B3'
    - '#BDF3F3'
  brandStrength: 0.0625
  lightness: 0.4
  saturation: 0.6085106
  rhythmicContrast: 0.5510638
purpose: []
