title: Home Vegetable Garden Specialists
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6085106
  brandStrength: 0.0625
  lightness: 0.4
  brandColors:
    - '#033001'
    - '#1FE903'
    - '#415D6E'
    - '#92A3B3'
    - '#BDF3F3'
  rhythmicContrast: 0.5510638
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: The Garden Brothers
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2382979
layout_spectrum: 0.4617021
