name: The Garden Brothers
favicon: null
layout_spectrum: 0.9325475709047168
typography_spectrum: 0.4657732928171754
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030801'
    - '#5a7611'
    - '#2e3e05'
    - '#80b01e'
    - '#deab65'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
